### ISSUE TITLE
Train Symbol Trains Tab shows wrong Start Time

### ISSUE THREAD

**Issue by CSX8600** [Mesabrook-Development-Team/MesaSuite#143]
The start time should show the earliest on duty time.
![image](https://user-images.githubusercontent.com/23085858/218164130-54b48245-7d69-477e-8350-932d4ee118a9.png)
In this case, it should show 2/6/2023 20:30
![image](https://user-images.githubusercontent.com/23085858/218164198-44fff8c8-3a1b-4ea6-a04f-9979fdd419d5.png)

**Comment by RavenholmZombie** [comment]
skill issue tbh
