### ISSUE TITLE
Add FileType for CraftTweaker scripts

### ISSUE THREAD

**Issue by CSX8600** [Mesabrook-Development-Team/MesaSuite#165]
**REQUIRED FOR NEXT MODPACK UPDATE!**

Both servers and clients need to be able to download CraftTweaker scripts. This will require a new file type to be added into MesaSuite. They will be placed in a folder called `scripts` that is located inside the `.minecraft` folder (for example - `%appdata%/.minecraft/scripts`).

**Comment by KreativeKngYT** [comment]
NOTE: CraftTweaker scripts are saved as a **.zs** file.
